version: '3.9'

services:
  postgres:
    # Use a set version to secure code from minor changes on the latests image version
    image: postgres:16.4-alpine  
    container_name: vita_mojo_test
    environment:
      # These variables would ideally be stored in 
      # AWS SecretsManager/other in non-test environments
      POSTGRES_DB: mydatabase  
      POSTGRES_USER: myuser 
      POSTGRES_PASSWORD: mypassword 
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data  # Mount the named volume for data persistence

  postgres_test:
    # Use a set version to secure code from minor changes on the latests image version
    image: postgres:16.4-alpine  
    container_name: vita_mojo_test_development
    environment:
      # These variables would ideally be stored in 
      # AWS SecretsManager/other in non-test environments
      POSTGRES_DB: mydatabase  
      POSTGRES_USER: myuser 
      POSTGRES_PASSWORD: mypassword 
    ports:
      - "5433:5432" 
      
volumes:
  pgdata:
    driver: local  # Use the local driver for the volume